[package]
name = "cadcraft"
description = "CADCraft desktop app"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false
default-run = "cadcraft"

[lints]
workspace = true

[package.metadata.generate-rpm]
assets = [
    { source = "target/release/cadcraft", dest = "/usr/bin/cadcraft", mode = "755" }
]

[dependencies]
cadcraft-engine = { workspace = true }
cadcraft-ui-martensite = { workspace = true }
tracing.workspace = true
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[build-dependencies]
winresource = "0.1"
